/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Vpacker */

#ifndef _Included_Vpacker
#define _Included_Vpacker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Vpacker
 * Method:    compress32
 * Signature: ([I[BJ)J
 */
JNIEXPORT jlong JNICALL Java_Vpacker_compress32
  (JNIEnv *, jclass, jintArray, jbyteArray, jlong);

/*
 * Class:     Vpacker
 * Method:    compress64
 * Signature: ([J[BJ)J
 */
JNIEXPORT jlong JNICALL Java_Vpacker_compress64
  (JNIEnv *, jclass, jlongArray, jbyteArray, jlong);

/*
 * Class:     Vpacker
 * Method:    uncompress32
 * Signature: ([B[IJ)J
 */
JNIEXPORT jlong JNICALL Java_Vpacker_uncompress32
  (JNIEnv *, jclass, jbyteArray, jintArray, jlong);

/*
 * Class:     Vpacker
 * Method:    uncompress64
 * Signature: ([B[JJ)J
 */
JNIEXPORT jlong JNICALL Java_Vpacker_uncompress64
  (JNIEnv *, jclass, jbyteArray, jlongArray, jlong);

/*
 * Class:     Vpacker
 * Method:    compress32_bound
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Vpacker_compress32_1bound
  (JNIEnv *, jclass, jlong);

/*
 * Class:     Vpacker
 * Method:    compress64_bound
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_Vpacker_compress64_1bound
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
