def options(opt):
  opt.load('compiler_cxx waf_unit_test')

def configure(ctx):
  ctx.load('compiler_cxx waf_unit_test')

def build(bld):
  bld.shlib(source='Vpacker.cpp',
            includes = '. ..',
            target='vpackj',
            defines='NDEBUG',
            cxxflags = '-O2 -fomit-frame-pointer -march=nocona')
